//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_01_Krasnova
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingList
    {
        public int ReadingListID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public int ListTypeID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ListType ListType { get; set; }
        public virtual User User { get; set; }
    }
}
