//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_01_Krasnova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Reason { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
